name: antios
options:
  bundleIdPrefix: com.antianxiety
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "14.2"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.7"

targets:
  antios:
    type: application
    platform: iOS
    sources:
      - antios
    resources:
      - antios/Resources
    settings:
      base:
        INFOPLIST_FILE: antios/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.antianxiety.antios
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Supabase
      - package: KeychainAccess
      - package: Alamofire
    entitlements:
      path: antios/antios.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access:
          - health-records

  antiosTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - antiosTests
    dependencies:
      - target: antios

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: "5.8.0"
