name: Build and Push to Aliyun ACR

on:
  push:
    branches:
      - master
  manual: {}

env:
  REGISTRY: crpi-7sdjjtp0a37i7b0r.cn-guangzhou.personal.cr.aliyuncs.com
  NAMESPACE: nomoreanxious
  IMAGE_NAME: nomoreanxious

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun ACR
        run: |
          echo "${{ secrets.ALIYUN_ACR_PASSWORD }}" | docker login \
            --username "${{ secrets.ALIYUN_ACR_USERNAME }}" \
            --password-stdin $REGISTRY

      - name: Verify required secrets
        run: |
          test -n "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" || (echo "NEXT_PUBLIC_SUPABASE_URL missing" && exit 1)
          test -n "${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" || (echo "NEXT_PUBLIC_SUPABASE_ANON_KEY missing" && exit 1)
          echo "Secrets are configured."

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          pull: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ gitee.sha }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}